sudo: required
language: generic

# Specify docker as a dependency
services:
  - docker

# Build test version of React project
before_install:
  - docker build -t allanjales-aja/react-test -f ./client/Dockerfile.dev ./client

# Run tests
script:
  - docker run -e CI=true allanjales-aja/react-test npm test

# Build prod versions of all projects
after_success:
  - docker build -t allanjales-aja/multi-client ./client
  - docker build -t allanjales-aja/multi-nginx ./nginx
  - docker build -t allanjales-aja/multi-server ./server
  - docker build -t allanjales-aja/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push allanjales-aja/multi-client
  - docker push allanjales-aja/multi-nginx
  - docker push allanjales-aja/multi-server
  - docker push allanjales-aja/multi-worker
